version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 14
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
        - pip install django
        - pip install djangorestframework
        - pip install pillow
  build:
    commands:
        - echo Build started
        - ng build
        - cd splitto
        - python manage.py runserver
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
